# Generated by Django 3.2.7 on 2021-09-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='times_played',
            field=models.IntegerField(default=0),
        ),
    ]
