# Generated by Django 3.2.7 on 2021-09-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_scoreboard_times_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='times_played',
            field=models.IntegerField(default=1),
        ),
    ]
